# Kit Progression
# [NUMBER] DEFAULT: 0
kit-progression: 0

# List of guest players
guests:
- PLAYER
- PLAYER

# Progression 0 Map
# [ITEMTYPE.TYPE.VALUE] (SEE: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html, https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html)
progression0-map:
- WORLDBORDER.500
- ITEM.ENCHANTED_GOLDEN_APPLE.LIMIT.1
- ITEM.GOLDEN_APPLE.LIMIT.16
- ITEM.COBWEB.LIMIT.16
- ITEM.ENDER_PEARL.LIMIT.3
- ITEM.WIND_CHARGE.LIMIT.0
- ITEM.EXPERIENCE_BOTTLE.LIMIT.0
- ITEM.TOTEM_OF_UNDYING.LIMIT.0
- ITEM.NETHERITE_SWORD.LIMIT.0
- ITEM.NETHERITE_AXE.LIMIT.0
- ITEM.NETHERITE_PICKAXE.LIMIT.0
- ITEM.NETHERITE_SHOVEL.LIMIT.0
- ITEM.NETHERITE_HOE.LIMIT.0
- ITEM.NETHERITE_HELMET.LIMIT.0
- ITEM.NETHERITE_CHESTPLATE.LIMIT.0
- ITEM.NETHERITE_LEGGINGS.LIMIT.0
- ITEM.NETHERITE_BOOTS.LIMIT.0
- ITEM.POTION.LIMIT.0
- ITEM.SPLASH_POTION.LIMIT.0
- ITEM.LINGERING_POTION.LIMIT.0
- ENCHANT.PROTECTION.LIMIT.2
- ENCHANT.UNBREAKING.LIMIT.1
- ENCHANT.SHARPNESS.LIMIT.2
- ENCHANT.EFFICIENCY.LIMIT.3
- ENCHANT.POWER.LIMIT.1
- ENCHANT.DEPTH_STRIDER.LIMIT.1
- ENCHANT.SOUL_SPEED.LIMIT.1
- ENCHANT.FEATHER_FALLING.LIMIT.2
- ENCHANT.PIERCING.LIMIT.1
- ENCHANT.QUICK_CHARGE.LIMIT.1
- ENCHANT.MENDING.LIMIT.0
- ENCHANT.KNOCKBACK.LIMIT.0
- ENCHANT.FIRE_ASPECT.LIMIT.0
- ENCHANT.FLAME.LIMIT.0
- ENCHANT.PUNCH.LIMIT.0
- ENCHANT.RIPTIDE.LIMIT.0
- ENCHANT.THORNS.LIMIT.0

progression1-map:
- WORLDBORDER.5000
- ITEM.ENCHANTED_GOLDEN_APPLE.LIMIT.4
- ITEM.GOLDEN_APPLE.LIMIT.64
- ITEM.COBWEB.LIMIT.64
- ITEM.ENDER_PEARL.LIMIT.6
- ITEM.WIND_CHARGE.LIMIT.16
- ITEM.EXPERIENCE_BOTTLE.LIMIT.192
- ITEM.TOTEM_OF_UNDYING.LIMIT.1
- ENCHANT.PROTECTION.LIMIT.3
- ENCHANT.KNOCKBACK.LIMIT.0
- ENCHANT.FIRE_ASPECT.LIMIT.0
- ENCHANT.FLAME.LIMIT.0
- ENCHANT.PUNCH.LIMIT.1
- ENCHANT.RIPTIDE.LIMIT.0
- ENCHANT.THORNS.LIMIT.0
- POTION.TURTLE_MASTER.COUNT.1
- POTION.STRENGTH.LIMIT.1
- POTION.SPEED.LIMIT.1
- POTION.WEAVING.LIMIT.1
- POTION.WEAVING.INVISIBILITY.1
